### ISSUE TITLE
Periodic Tasks ( Cron jobs ) with Http error 404

### ISSUE THREAD

**Issue by bookmebus** [tawan/active-elastic-job#101]
I have my cron.yaml setup as below

```yaml
# app_root/cron.yaml
version: 1
cron:
- name: "Cron::ExpiredPendingTicket"
  url: "/expired_pending_ticket"
  schedule: "*/5 * * * *"

- name: "Cron::AppCreditThresholdAlert"
  url: "/app_credit_threshold_alert"
  schedule: "0 16 * * *"

- name: "Cron::TicketReviewSending"
  url: "/ticket_review_sending"
  schedule: "0 10 * * *"

- name: "Cron::ExpiredTripUnpublisher"
  url: "/expired_trip_unpublisher"
  schedule: "0 10 * * *"

- name: "Cron::SmsMarketing"
  url: "/sms_marketing"
  schedule: "0 0 * * *"
```

I got this in my /var/log/support/access.log

127.0.0.1 - - [08/Feb/2019:03:20:00 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"
127.0.0.1 - - [08/Feb/2019:03:20:00 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"
127.0.0.1 - - [08/Feb/2019:03:20:00 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"
127.0.0.1 - - [08/Feb/2019:03:20:00 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"
127.0.0.1 - - [08/Feb/2019:03:20:00 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"
127.0.0.1 - - [08/Feb/2019:03:21:22 +0000] "POST /expired_pending_ticket HTTP/1.1" 404 0 "-" "aws-sqsd/2.4"

and this in /var/log/aws-sqsd/access.log

2019-02-08T03:25:00Z message: sent to http://localhost:80/expired_pending_ticket
2019-02-08T03:25:00Z message: sent to http://localhost:80/expired_pending_ticket
2019-02-08T03:25:00Z message: sent to http://localhost:80/expired_pending_ticket
2019-02-08T03:25:00Z message: sent to http://localhost:80/expired_pending_ticket
2019-02-08T03:25:00Z http-err: 0d0211bf-8dcb-451a-8325-f0581281bcb2 (5) 404 - 0.032
2019-02-08T03:25:00Z http-err: 78a45071-b76c-4e4e-8346-64410e0c9a97 (3) 404 - 0.032
2019-02-08T03:25:00Z http-err: 9604b106-b640-4c1b-9223-5228073969a4 (9) 404 - 0.032

```ruby
#app/models/cron/expired_pending_ticket.rb
class Cron::ExpiredPendingTicket < Cron::Base
  def perform(*args)
    TicketOrderPending.new.mark_as_cancel
    TicketOrderUnpaid.new.mark_as_cancel
    Transit::ReservationCartPending.new.mark_as_cancel
  end
end
```

```ruby
#app/models/cron/base.rb
if Rails.env.development? || Rails.env.test?
  class Cron::Base
    include Sidekiq::Worker
  end
else
  class Cron::Base < ::ActiveJob::Base
  end
end
```

Any idea what can be wrong with  my setup? Thanks for making this gem possible with eb.

**Comment by bookmebus** [comment]
solved this with url: '/periodic_tasks' like this:

```yaml
# the gem listen to /periodic_tasks
version: 1
cron:
- name: "Cron::ExpiredPendingTicket"
  url: "/periodic_tasks"
  schedule: "*/5 * * * *"

- name: "Cron::AppCreditThresholdAlert"
  url: "/periodic_tasks"
  schedule: "*/10 * * * *"
  # schedule: "0 16 * * *"

- name: "Cron::TicketReviewSending"
  url: "/periodic_tasks"
  schedule: "*/12 * * * *"
  # schedule: "0 10 * * *"

- name: "Cron::ExpiredTripUnpublisher"
  url: "/periodic_tasks"
  schedule: "*/15 * * * *"
  # schedule: "0 10 * * *"

- name: "Cron::SmsMarketing"
  url: "/periodic_tasks"
  schedule: "*/20 * * * *"
  # schedule: "0 0 * * *"


```
