### ISSUE TITLE
Support for Elastic Beanstalk's Periodic Tasks? (via cron.yml)

### ISSUE THREAD

**Issue by briantigerchow** [tawan/active-elastic-job#40]
Does this library support Elastic Beanstalk's [periodic tasks](http://docs.aws.amazon.com/elasticbeanstalk/latest/dg/using-features-managing-env-tiers.html#worker-periodictasks) via `cron.yml` file? I do not see documentation for such a feature.

**Comment by briantigerchow** [comment]
If not, here is my basic implementation that I am using now:

``` yaml
version: 1
cron:
      - name: 'HeartbeatJob'
        url: '/_jobs/heartbeat'
        schedule: "*/30 * * * * *"
      - name: 'FetchStreamMetricsJob'
        url: '/_jobs/fetch_stream_metrics'
        schedule: "*/5 * * * * *"
```

``` ruby
Rails.application.routes.draw do
  post '_jobs/:job', to: 'job_runner#perform_now'
end
```

``` ruby
class JobRunnerController < ApplicationController
  def perform_now

    # job_name e.g. 'fetch_stream_metrics' for # FetchStreamMetricsJob

    job_name = params[:job]
    job = "#{job_name}_job".titleize.gsub(' ', '').constantize.new
    job.perform_now
  end
end
```
